### ISSUE TITLE
Fix: Server raises QueryFailedError: Cannot delete or update a parent row: a foreign key constraint fails ...

### ISSUE THREAD

**Issue by vimkim** [boostcampwm2023/web15-BaekjoonRooms#193]
<img width="788" alt="image" src="https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/18080546/bca48584-bece-41cf-8f06-fbe717cbf259">

```
1210 02:26:26 ERR [Exceptions] Server raises Error QueryFailedError: Cannot delete or update a parent row: a foreign key constraint fails (`example_dbname`.`submission`, CONSTRAINT `FK_b670000e187e1a6fa5c65f2eceb` FOREIGN KEY (`room_id`) REFERENCES `room` (`id`))
QueryFailedError: Cannot delete or update a parent row: a foreign key constraint fails (`example_dbname`.`submission`, CONSTRAINT `FK_b670000e187e1a6fa5c65f2eceb` FOREIGN KEY (`room_id`) REFERENCES `room` (`id`))
    at Query.onResult (/home/dkubnt/github/bojrooms/develop/server/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.execute (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Socket.Readable.push (node:internal/streams/readable:245:10)
1210 02:26:26 ERR [Exceptions] Cannot delete or update a parent row: a foreign key constraint fails (`example_dbname`.`submission`, CONSTRAINT `FK_b670000e187e1a6fa5c65f2eceb` FOREIGN KEY (`room_id`) REFERENCES `room` (`id`))
QueryFailedError: Cannot delete or update a parent row: a foreign key constraint fails (`example_dbname`.`submission`, CONSTRAINT `FK_b670000e187e1a6fa5c65f2eceb` FOREIGN KEY (`room_id`) REFERENCES `room` (`id`))
    at Query.onResult (/home/dkubnt/github/bojrooms/develop/server/src/driver/mysql/MysqlQueryRunner.ts:222:33)
    at Query.execute (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/commands/command.js:36:14)
    at PoolConnection.handlePacket (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/connection.js:478:34)
    at PacketParser.onPacket (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/dkubnt/github/bojrooms/develop/server/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)
    at Socket.Readable.push (node:internal/streams/readable:245:10)
<<<-- [12/10/2023, 02:26:26] 500 Internal Server Error 61.794 52
1210 02:26:26 DEB [SocketGate] client mockuser1 leaving room C46E40 and disconnecting...

-->>> [12/10/2023, 02:26:26] ::1 - "GET /session HTTP/1.1"
1210 02:26:26 DEB [LocalSeria] Deserializing userSession...
1210 02:26:26 DEB [LocalSeria] { provider: 'mock1', providerId: 'mock1', username: 'mockuser1' }
1210 02:26:26 DEB [SessionAut] start canActivate
1210 02:26:26 DEB [SessionAut] isAuthenticated is true
<<<-- [12/10/2023, 02:26:26] 200 OK 5.788 183
```

**Comment by dqgthb** [comment]
submission에서 cascade: true 제거
